"""create models

Revision ID: 9cbf36642e24
Revises: 
Create Date: 2025-04-04 20:30:10.787750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbf36642e24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('QUIZ', 'CODE', name='tasktype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('short_verdict', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('code_solution_type', sa.Enum('STR', 'ZIP', name='submissiontype'), nullable=True),
    sa.Column('compiler_name', sa.String(), nullable=True),
    sa.Column('main_file', sa.String(), nullable=True),
    sa.Column('group_scores', sa.JSON(), nullable=True),
    sa.Column('detailed_verdict', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solutions')
    # ### end Alembic commands ###
