# Generated by Django 5.0.2 on 2024-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('compiler', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('group_points', models.JSONField(default=dict)),
                ('protocol', models.JSONField(blank=True, default=list)),
                ('is_solved', models.BooleanField(default=False)),
                ('verdict', models.CharField(default='NC')),
                ('submission_type', models.CharField(choices=[('str', 'String'), ('zip', 'Zip')], max_length=3)),
                ('submission_data', models.TextField()),
                ('status', models.CharField(choices=[('nc', 'Not Checked'), ('ip', 'In Progress'), ('cc', 'Checked'), ('ie', 'Internal Error')], default='nc', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('points', models.IntegerField()),
                ('is_solved', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
