global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'solution_service'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'solution.service:8000' ]

  - job_name: 'contest_service'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'contest.service:8000' ]

  - job_name: 'account_service'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'account.service:8000' ]

  - job_name: 'nginx'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'promexporter.service:9113' ]


#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - 'alertmanager:9093'
