apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    uid: fed57fqnvpb7kf
    type: postgres
    url: db:5432
    user: pguser
    secureJsonData:
      password: 'pgpass'
    jsonData:
      database: prodadvert_db
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false


  - name: prometheus
    type: prometheus
    uid: bed67290di3nka
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
