apiVersion: 1


datasources:
  - name: Prometheus
    type: prometheus
    uid: behw3dv3ave9sd
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: POST
    readOnly: false

  - uid: fehtgudue4sn4b
    name: loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
