{
 "title": "Main APIs monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target_service",
    "label": "Target service",
    "query": "account_service,contest_service,solution_service"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests count",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path, method) (litestar_requests_total{path!=\"/metrics\", job=\"$target_service\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, method) (rate(litestar_requests_total{path!=\"/metrics\", job=\"$target_service\"}[30s]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Service logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\"dockingjudge-${target_service}-.+\"}"
    }
   ]
  },
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(litestar_requests_total{job=\"$target_service\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}