{
 "title": "Nginx monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 15, "x": 7, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"dockingjudge-api_gateway-1\"}"
    }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reading connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accepted  connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_accepted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Writing connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_writing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Handled connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "__auto" }
   ]
  }
 ]
}