"""add submitted_at

Revision ID: 1963e77cf1d0
Revises: 26d806c70e96
Create Date: 2025-01-30 15:58:09.478681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1963e77cf1d0'
down_revision: Union[str, None] = '26d806c70e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('submitted_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'submitted_at')
    # ### end Alembic commands ###
