"""add fields

Revision ID: 26d806c70e96
Revises: f3b4682c44a1
Create Date: 2025-01-16 09:26:01.723435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d806c70e96'
down_revision: Union[str, None] = 'f3b4682c44a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('code_solution_type', sa.Enum('STR', 'ZIP', name='submissiontype'), nullable=True))
    op.add_column('solutions', sa.Column('compiler_name', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('main_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'main_file')
    op.drop_column('solutions', 'compiler_name')
    op.drop_column('solutions', 'code_solution_type')
    # ### end Alembic commands ###
