# Generated by Django 5.0.2 on 2025-10-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiztask_points_alter_contest_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztask',
            name='validator',
            field=models.JSONField(default=dict),
        ),
    ]
